use_frameworks!

target 'BMAssetPicker_Example' do
    pod 'BMAssetPicker', :path => '../'
    
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    target 'BMAssetPicker_Tests' do
        inherit! :search_paths
        
        
    end
end
